name: Build

on: [push]

jobs:
  build:
    name: SSH debug
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3
      
      - uses: fawazahmed0/action-debug@main
